sudo: false
language: ruby
script: rake test spec:javascripts
rvm:
  - 2.2.4
  - 2.3.0
before_script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz && tar -xzvf geckodriver-v0.16.1-linux64.tar.gz
  - mkdir drivers && mv ./geckodriver drivers/
  - export PATH="$PATH:./drivers/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
addons:
  firefox: "latest"
